name: Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install
        run: npm ci
        
      - name: Build
        run: npm run build
      
      - name: Copy index.html
        run: |
          cp index.html dist/index.html
        
      - name: Copy css
        run: |
          mkdir -p dist/css
          cp css/reset.css dist/css/
          
          
      - name: Copy img
        run: |
          mkdir -p dist/img
          cp img/* dist/img/
        
      - name : Deploy
        uses : JamesIves/github-pages-deploy-action@v4.2.3 
        with :
          branch : gh-pages
          folder : dist
